### ISSUE TITLE
PRACTICA1-EQUIPO-DANONINO

### ISSUE THREAD

**Issue by Kim-Mendoza3** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-danonino-programmers#2]
Reporte: 
https://drive.google.com/file/d/1WVxU35he-bbM82CkEOclVfe4Im8f35WS/view?usp=sharing

Diseño de Figma:
https://www.figma.com/file/FrMba9BuS9OcovIhNlddWj/MOCKUP?type=design&node-id=0%3A1&mode=design&t=5oNsjac1DV4ax2Ba-1

INTEGRANTES: 
LOPEZ PEREZ ANGEL ANTONIO
MENDOZA HERNANDEZ KIMBERLY
VASQUEZ REYES GIBRAN JESUS

**Comment by ElisabetRD** [comment]
19% Faltan resultados

**Comment by josealfredo79** [comment]
Bien hecho favor de atender los resultados..ñpor favor...
